version: "3"
services:
  school_api:
    container_name: schooldb
    hostname: schooldb
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=sha256_password
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
